site:
    siteURL: "https://cybalp.me/"
    title: "CybAlp"
    subtitle: "| Root"
    lang: "en"
    translate:
        enable: true
        service: "client.edge"
        showSelectTag: true
        autoDiscriminate: true
        ignoreClasses:
            - "ignore"
            - "banner-title"
            - "banner-subtitle"
        ignoreTags:
            - "script"
            - "style"
            - "code"
            - "pre"
    timeZone: 8
    font:
        "Exo":
            src: "https://fonts.googleapis.com/css2?family=Exo:ital,wght@0,100..900;1,100..900&display=swap"
            family: "Exo"
    themeColor:
        hue: 255
    defaultTheme: "dark"
    wallpaper:
        mode: "banner"
        src:
            desktop:
                - "/assets/images/wallpaper.png"
                - "/assets/images/red.png"
            mobile:
                - "/assets/images/wallpaper.png"
                - "/assets/images/red.png"
        position: "center"
        carousel:
            enable: false
            interval: 3.6
            kenBurns: false
        banner:
            homeText:
                enable: true
                title: "CybAlp"
                subtitle:
                    - "ᴀ ᴄʏʙᴇʀꜱᴇᴄᴜʀɪᴛʏ ⚔ - ᴀ ʟɪɴᴜx ᴇɴᴛʜᴜꜱɪᴀꜱᴛ 𓅷 - ᴀ ᴄᴏᴅᴇʀ </>"
                typewriter:
                    enable: true
                    speed: 100
                    deleteSpeed: 50
                    pauseTime: 1000
            credit:
                enable: true
                text: "Support Me ∞ ♡"
                url: "https://github.com/cybalp#supports-me--"
            navbar:
                transparentMode: "full"
            waves:
                enable: true
                performanceMode: false
        fullscreen:
            zIndex: -1
            opacity: 0.9
            blur: 5
            navbar:
                transparentMode: "semi"
    loadingOverlay:
        enable: true
        title:
            enable: true
            content: "RUN!"
            interval: 1.5
        spinner:
            enable: true
            interval: 3
    favicon: []
    bangumi:
        userId: ""
    generateOgImages: true

umami:
    enabled: false
    baseUrl: "https://api.umami.is"
    apiKey: ""
    scripts: ""

navbar:
    
    links:
        - 
            "Home"
        - 
            "Archive"
        - 
            name: "Skills & Hobbies"
            url: "/skills-hobbies/"
            icon: "material-symbols:person"
            description: "A collection of my creative works and experiences"
            children:
                - 
                    "Projects"
                - 
                    "Skills"
                - 
                    "Timeline"
                - 
                    "Diary"
                - 
                    "Albums"
        - 
            "About"

sidebar:
    components:
        left:
            - 
                type: "profile"
                position: "top"
            -
                type: "announcement"
                position: "top"
            - 
                type: "categories"
                position: "sticky"
                responsive:
                    collapseThreshold: 5
                depth: 3
            -
                type: "tags"
                position: "sticky"
                responsive:

                    collapseThreshold: 20

        right:
            -
                type: "toc"
                position: "sticky"
                depth: 3
            - 
                type: "statistics"
                position: "sticky"
                visibility:
                    mode: "include"
                    paths: ["^/$", "^/archive$"]
profile:
    avatar: "/assets/images/profile.png"
    name: "Alp"
    bio: "A non-professional blog. Personal documentation and a graveyard of personal thoughts."
    links:
        - 
            name: "GitHub"
            icon: "fa6-brands:github"
            url: "https://github.com/cybalp"
        - 
            name: "LinkedIn"
            icon: "fa6-brands:linkedin"
            url: "https://www.linkedin.com/in/alpulkegul"
        - 
            name: "IG"
            icon: "fa6-brands:instagram"
            url: "https://instagram.com/cybalp"


announcement:
    title: "Announcement"
    content: "----"
    closable: false
    link:
        enable: true
        text: "Learn More"
        url: "/about/"
        external: false

post:
    showLastModified: true
    expressiveCode:
        theme: "github-dark"
    license:
        enable: true
        name: "CC BY-NC-SA 4.0"
        url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    comment:
        enable: false
        twikoo:
            envId: "https://twikoo.vercel.app"
            lang: "en"
footer:
    enable: false
    customHtml: ""

particle:
    enable: true
    particleNum: 12
    limitTimes: -1
    size:
        min: 0.3
        max: 0.9
    opacity:
        min: 0.3
        max: 0.9
    speed:
        horizontal:
            min: -0.9
            max: 0.9
        vertical:
            min: 0.15
            max: 0.3
        rotation: 0.12
        fadeSpeed: 0.12
    zIndex: 100

musicPlayer:
    enable: false
    mode: "meting"
    meting:
        meting_api: "https://api.i-meto.com/meting/api"
        server: "netease"
        type: "playlist"
        id: "2161912966"
    local:
        playlist:
            - 
                id: 1
                title: "深海之息"
                artist: "Youzee Music"
                cover: "https://p1.music.126.net/PhKOqFtljgHDDpKYM2ADUA==/109951169858309716.jpg"
                url: "assets/music/深海之息.m4a"
                lrc: "assets/music/深海之息.lrc"
                duration: 146
    autoplay: true

pio:
    enable: false
    models:
        - "/pio/models/pio/model.json"
    position: "left"
    width: 280
    height: 250

    mode: "draggable"

    hiddenOnMobile: true
    dialog:
        welcome: "Welcome!"
        touch:
            - "What are you doing?"
            - "Stop touching me!"
            - "Don't bully me like that!"
            - "(｡í _ ì｡)"
        home: "Click here to go back to homepage!"
        skin:
            - "Want to see my new outfit?"
            - "The new outfit looks great~"
        close: "See you next time~"
        link: "https://nav.kungal.org"