// ❯ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ❯ @status OK!
// ❯ @path ./src/env.d.ts
// ❯ @desc Astro ambient type references — client types and auto-generated collection/route types
// ❯ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// ❯ REFERENCES
// ❯ @docs Adds import.meta.env typings and Astro globals
// ❯ @docs Auto-generated by astro dev/check — never edit manually
/// <reference types="astro/client" />
/// <reference path="../.astro/types.d.ts" />
